#!/usr/bin/env python3
"""Build a simple Markdown file index for the knowledge base."""
from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "generated-index.md"
SCAN_DIRS = ["kb", "literature", "data", "experiments", "prompts", "docs", "decisions"]


def frontmatter_value(text: str, key: str) -> str:
    if not text.startswith("---\n"):
        return ""
    end = text.find("\n---", 4)
    if end == -1:
        return ""
    block = text[4:end]
    m = re.search(rf"^\s*{re.escape(key)}\s*:\s*(.+?)\s*$", block, re.MULTILINE)
    return m.group(1).strip().strip('"') if m else ""


def first_heading(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def main() -> int:
    rows = []
    for directory in SCAN_DIRS:
        base = ROOT / directory
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.md")):
            rel = path.relative_to(ROOT).as_posix()
            text = path.read_text(encoding="utf-8")
            title = frontmatter_value(text, "title") or first_heading(text) or path.stem
            status = frontmatter_value(text, "status") or ""
            rows.append((rel, title, status))

    lines = [
        "# Generated Index",
        "",
        "This file is generated by `scripts/build_index.py`.",
        "",
        "| Path | Title | Status |",
        "|---|---|---|",
    ]
    for rel, title, status in rows:
        lines.append(f"| [`{rel}`](../{rel}) | {title} | {status} |")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(rows)} entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
